feat(add): final project

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,79 +1,85 @@
 name: Chocolatine
-
+run-name: ${{github.actor}} checker chocolatine
 on:
   push:
     branches:
       - '*'
-      - '!ga-ignore-*'
+      - 'ga-ignore-*'
   pull_request:
     branches:
       - '*'
-      - '!ga-ignore-*'
+      - 'ga-ignore-*'
 
 env:
-  MIRROR_URL: git@github.com:EpitechPromo2028/B-DOP-200-PAR-2-1-chocolatine-zoltan.babko.git
-  EXECUTABLES: "directory1/executableA,directory2/executableB"
-  GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+  MIRROR_URL: "git@github.com:zoltanbabko/chocolatine.git"
+  EXECUTABLES: "fazzbizz"
 
 jobs:
   check_coding_style:
     name: Check Coding Style
     runs-on: ubuntu-latest
+    container: ghcr.io/epitech/coding-style-checker:latest
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-
-      - name: Run Coding Style Checker
-        run: |
-          docker run --rm -v $(pwd):/workspace ghcr.io/epitech/coding-style-checker:latest ; check.sh $(pwd) $(pwd)
-
+      - uses: actions/checkout@v3
+      - id: check_coding_style
+        name: Run coding-style
+        run: check.sh . /tmp
+      - run: |
+          input=/tmp/coding-style-reports.log
+          while IFS= read -r -a line; do
+            fields=($(printf "%s" "$line"|cut -d':' --output-delimiter=' ' -f1-))
+            echo "::error title=${fields[2]} coding style error,file=${fields[0]},line=${fields[1]}::${fields[3]}"
+          done < $input
+      - run: |
+          NB_ERROR=$(cat /tmp/coding-style-reports.log | wc -l)
+          if [ $NB_ERROR -gt 0 ]; then
+            echo Coding style error detected
+            exit 1
+          fi
+    
   check_program_compilation:
     name: Check Program Compilation
-    runs-on: epitechcontent/epitest-docker
+    runs-on: ubuntu-latest
     timeout-minutes: 2
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-
-      - name: Make
+    container: epitechcontent/epitest-docker:latest
+    needs: check_coding_style
+    steps:  
+      - uses: actions/checkout@v3
+      - id: check_program_compilation
         run: make
-        timeout-minutes: 2
-
-      - name: Make Clean
-        run: make clean
-
-      - name: Verify Executables
-        run: |
-          IFS=',' read -ra EXECUTABLES_ARRAY <<< "$EXECUTABLES"
-          for executable in "${EXECUTABLES_ARRAY[@]}"; do
-            if [ ! -x "$executable" ]; then
-              echo "Error: $executable missing or not executable"
+      - run: make clean 
+      - run: |
+          for file in ${{ env.EXECUTABLES }};do
+            if [ ! -x "$file" ]; then
+              echo "File $file not here or not executable"
               exit 1
             fi
           done
 
   run_tests:
-    name: Run Tests
-    runs-on: epitechcontent/epitest-docker
+    name: Runs tests
+    needs: check_program_compilation
+    runs-on: ubuntu-latest
     timeout-minutes: 2
+    container: epitechcontent/epitest-docker:latest
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-
-      - name: Make Tests
+      - uses: actions/checkout@v3
+      - id: run_tests
         run: make tests_run
-        timeout-minutes: 2
 
   push_to_mirror:
-    name: Push Mirror Repository
+    name: Push To Mirror
     runs-on: ubuntu-latest
+    needs:  run_tests
     if: github.event_name == 'push'
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-
-      - name: Push to Mirror
-        uses: pixta-dev/repository-mirroring-action@v1
+      - uses: actions/checkout@v3
         with:
-          target_repo_url: ${{ env.MIRROR_URL }}
-          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+          fetch-depth: 0
+      - uses: pixta-dev/repository-mirroring-action@v1
+        with:
+          target_repo_url:
+            ${{ env.MIRROR_URL }}
+          ssh_private_key:
+            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+        
